package catalog

func DefaultCatalog() ServiceCatalog {
	return ServiceCatalog{
		Version: "v1",
		Services: []ServiceTemplate{
			{
				Key:             "slack",
				Label:           "Slack",
				Description:     "Slack Web API + Socket Mode credentials.",
				ConnectionID:    "slack-proxy",
				BaseURL:         "https://slack.com/api",
				AuthMode:        "bearer",
				AuthHeaderName:  "Authorization",
				AuthPrefix:      "Bearer ",
				AuthSecretKey:   "bot_token",
				DefaultTestPath: "/auth.test",
				CredentialFields: []CredentialField{
					{Key: "bot_token", Label: "Bot Token", Placeholder: "Paste bot token", Secret: true, Required: true},
					{Key: "app_token", Label: "App Token", Placeholder: "Paste app token", Secret: true, Required: true, Help: "Used by Socket Mode clients."},
				},
			},
			{
				Key:             "discord",
				Label:           "Discord",
				Description:     "Discord bot token.",
				ConnectionID:    "discord-proxy",
				BaseURL:         "https://discord.com/api/v10",
				AuthMode:        "bearer",
				AuthHeaderName:  "Authorization",
				AuthPrefix:      "Bot ",
				AuthSecretKey:   "bot_token",
				DefaultTestPath: "/users/@me",
				CredentialFields: []CredentialField{
					{Key: "bot_token", Label: "Bot Token", Placeholder: "Paste bot token", Secret: true, Required: true},
				},
			},
			{
				Key:             "whatsapp",
				Label:           "WhatsApp",
				Description:     "WhatsApp Cloud API access token.",
				ConnectionID:    "whatsapp-proxy",
				BaseURL:         "https://graph.facebook.com",
				AuthMode:        "bearer",
				AuthHeaderName:  "Authorization",
				AuthPrefix:      "Bearer ",
				AuthSecretKey:   "access_token",
				DefaultTestPath: "/",
				CredentialFields: []CredentialField{
					{Key: "access_token", Label: "Access Token", Placeholder: "Paste token", Secret: true, Required: true},
				},
			},
			{
				Key:             "telegram",
				Label:           "Telegram",
				Description:     "Telegram bot token.",
				ConnectionID:    "telegram-proxy",
				BaseURL:         "https://api.telegram.org",
				AuthMode:        "header_key",
				AuthHeaderName:  "X-Telegram-Bot-Token",
				AuthPrefix:      "",
				AuthSecretKey:   "bot_token",
				DefaultTestPath: "/",
				CredentialFields: []CredentialField{
					{Key: "bot_token", Label: "Bot Token", Placeholder: "Paste bot token", Secret: true, Required: true},
				},
			},
			{
				Key:             "github",
				Label:           "GitHub",
				Description:     "GitHub personal access token.",
				ConnectionID:    "github-proxy",
				BaseURL:         "https://api.github.com",
				AuthMode:        "bearer",
				AuthHeaderName:  "Authorization",
				AuthPrefix:      "Bearer ",
				AuthSecretKey:   "api_token",
				DefaultTestPath: "/user",
				CredentialFields: []CredentialField{
					{Key: "api_token", Label: "API Token", Placeholder: "Paste API token", Secret: true, Required: true},
				},
			},
			{
				Key:               "linear",
				Label:             "Linear",
				Description:       "Linear API key.",
				ConnectionID:      "sigilum-secure-linear",
				BaseURL:           "https://api.linear.app",
				MCPBaseURL:        "https://mcp.linear.app",
				AuthMode:          "header_key",
				AuthHeaderName:    "Authorization",
				AuthPrefix:        "",
				AuthSecretKey:     "api_key",
				MCPTransport:      "streamable_http",
				MCPEndpoint:       "/mcp",
				DefaultTestPath:   "/graphql",
				DefaultTestMethod: "POST",
				DefaultTestHeaders: map[string]string{
					"Content-Type": "application/json",
				},
				DefaultTestBody: `{"query":"query { viewer { id } }"}`,
				CredentialFields: []CredentialField{
					{Key: "api_key", Label: "API Key", Placeholder: "Paste API key", Secret: true, Required: true},
				},
			},
			{
				Key:             "notion",
				Label:           "Notion",
				Description:     "Notion integration token.",
				ConnectionID:    "notion-proxy",
				BaseURL:         "https://api.notion.com",
				AuthMode:        "bearer",
				AuthHeaderName:  "Authorization",
				AuthPrefix:      "Bearer ",
				AuthSecretKey:   "api_token",
				DefaultTestPath: "/v1/users/me",
				CredentialFields: []CredentialField{
					{Key: "api_token", Label: "API Token", Placeholder: "secret_...", Secret: true, Required: true},
				},
			},
			{
				Key:             "brave-search",
				Label:           "Brave Search",
				Description:     "Brave Search API key.",
				ConnectionID:    "brave-search-proxy",
				BaseURL:         "https://api.search.brave.com",
				AuthMode:        "header_key",
				AuthHeaderName:  "X-Subscription-Token",
				AuthPrefix:      "",
				AuthSecretKey:   "api_key",
				DefaultTestPath: "/res/v1/web/search?q=sigilum",
				CredentialFields: []CredentialField{
					{Key: "api_key", Label: "API Key", Placeholder: "Paste API key", Secret: true, Required: true},
				},
			},
			{
				Key:             "claude",
				Label:           "Claude (Anthropic)",
				Description:     "Anthropic API key.",
				ConnectionID:    "claude-proxy",
				BaseURL:         "https://api.anthropic.com",
				AuthMode:        "header_key",
				AuthHeaderName:  "x-api-key",
				AuthPrefix:      "",
				AuthSecretKey:   "api_key",
				DefaultTestPath: "/v1/messages",
				CredentialFields: []CredentialField{
					{Key: "api_key", Label: "API Key", Placeholder: "Paste API key", Secret: true, Required: true},
				},
			},
			{
				Key:             "openai",
				Label:           "OpenAI",
				Description:     "OpenAI API key.",
				ConnectionID:    "sigilum-secure-openai",
				BaseURL:         "https://api.openai.com",
				AuthMode:        "bearer",
				AuthHeaderName:  "Authorization",
				AuthPrefix:      "Bearer ",
				AuthSecretKey:   "api_key",
				DefaultTestPath: "/v1/models",
				CredentialFields: []CredentialField{
					{Key: "api_key", Label: "API Key", Placeholder: "Paste API key", Secret: true, Required: true},
				},
			},
			{
				Key:             "openai-image-gen",
				Label:           "OpenAI Image Gen",
				Description:     "OpenAI image generation key.",
				ConnectionID:    "openai-image-proxy",
				BaseURL:         "https://api.openai.com",
				AuthMode:        "bearer",
				AuthHeaderName:  "Authorization",
				AuthPrefix:      "Bearer ",
				AuthSecretKey:   "api_key",
				DefaultTestPath: "/v1/models",
				CredentialFields: []CredentialField{
					{Key: "api_key", Label: "API Key", Placeholder: "Paste API key", Secret: true, Required: true},
				},
			},
			{
				Key:             "openai-whisper-api",
				Label:           "OpenAI Whisper API",
				Description:     "OpenAI Whisper API key.",
				ConnectionID:    "openai-whisper-proxy",
				BaseURL:         "https://api.openai.com",
				AuthMode:        "bearer",
				AuthHeaderName:  "Authorization",
				AuthPrefix:      "Bearer ",
				AuthSecretKey:   "api_key",
				DefaultTestPath: "/v1/models",
				CredentialFields: []CredentialField{
					{Key: "api_key", Label: "API Key", Placeholder: "Paste API key", Secret: true, Required: true},
				},
			},
			{
				Key:             "gemini",
				Label:           "Gemini (Google AI)",
				Description:     "Google Gemini API key.",
				ConnectionID:    "gemini-proxy",
				BaseURL:         "https://generativelanguage.googleapis.com",
				AuthMode:        "header_key",
				AuthHeaderName:  "x-goog-api-key",
				AuthPrefix:      "",
				AuthSecretKey:   "api_key",
				DefaultTestPath: "/v1beta/models",
				CredentialFields: []CredentialField{
					{Key: "api_key", Label: "API Key", Placeholder: "Paste API key", Secret: true, Required: true},
				},
			},
			{
				Key:             "canvas",
				Label:           "Canvas LMS",
				Description:     "Canvas API token.",
				ConnectionID:    "canvas-proxy",
				BaseURL:         "https://canvas.instructure.com",
				PathPrefix:      "/api/v1",
				AuthMode:        "bearer",
				AuthHeaderName:  "Authorization",
				AuthPrefix:      "Bearer ",
				AuthSecretKey:   "api_token",
				DefaultTestPath: "/users/self/profile",
				CredentialFields: []CredentialField{
					{Key: "api_token", Label: "API Token", Placeholder: "Paste token", Secret: true, Required: true},
				},
			},
			{
				Key:             "typefully",
				Label:           "Typefully",
				Description:     "Typefully bearer token.",
				ConnectionID:    "typefully-proxy",
				BaseURL:         "https://api.typefully.com",
				MCPBaseURL:      "https://mcp.typefully.com",
				AuthMode:        "bearer",
				AuthHeaderName:  "Authorization",
				AuthPrefix:      "Bearer ",
				AuthSecretKey:   "bearer_token",
				MCPTransport:    "streamable_http",
				MCPEndpoint:     "https://mcp.typefully.com/mcp?TYPEFULLY_API_KEY={{__API_KEY__}}",
				DefaultTestPath: "/v1",
				CredentialFields: []CredentialField{
					{Key: "bearer_token", Label: "Bearer Token", Placeholder: "Paste bearer token", Secret: true, Required: true},
				},
			},
			{
				Key:               "typefully-mcp",
				Label:             "Typefully (MCP)",
				Description:       "Typefully MCP endpoint with query-parameter API key (https://mcp.typefully.com/mcp?TYPEFULLY_API_KEY={{__API_KEY__}}).",
				ConnectionID:      "sigilum-secure-typefully",
				Protocol:          "mcp",
				BaseURL:           "https://mcp.typefully.com",
				MCPBaseURL:        "https://mcp.typefully.com",
				AuthMode:          "query_param",
				AuthHeaderName:    "TYPEFULLY_API_KEY",
				AuthPrefix:        "",
				AuthSecretKey:     "__API_KEY__",
				MCPTransport:      "streamable_http",
				MCPEndpoint:       "https://mcp.typefully.com/mcp?TYPEFULLY_API_KEY={{__API_KEY__}}",
				DefaultTestPath:   "/mcp",
				DefaultTestMethod: "POST",
				DefaultTestHeaders: map[string]string{
					"Content-Type": "application/json",
				},
				DefaultTestBody: `{"jsonrpc":"2.0","id":"sigilum-test","method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"sigilum-gateway","version":"mvp"}}}`,
				CredentialFields: []CredentialField{
					{Key: "__API_KEY__", Label: "API Key", Placeholder: "Paste Typefully API key", Secret: true, Required: true},
				},
			},
		},
	}
}
